### PR TITLE
Add Hookdeck CLI

### PR DESCRIPTION
**Pull request by leggetter**
The Hookdeck platform is closed-source and has a free tier, but it is ultimately commercial.

The Hookdeck CLI works with the commercial offering but also allows anonymous connectivity without a Hookdeck account.

### CODE REVIEW

**Comment by anderspitman** [comment]
Hey @leggetter, sorry for the delay. Does Hookdeck work with arbitrary HTTP traffic, or just webhooks, ie can I run a webserver behind it?

Don't worry about the conflicts, I'll fix those if we end up merging.

**Comment by leggetter** [comment]
@anderspitman - yes, full pass-through support. Something I should flag - and happy to update the text description - is that because Hookdeck is purely asynchronous, the server response is not returned to the client that initiates the request. The initiating client will instead get a 200 OK for all valid requests, acknowledging that the request has been received.

**Comment by leggetter** [comment]
> @anderspitman - yes, full pass-through support. Something I should flag - and happy to update the text description - is that because Hookdeck is purely asynchronous, the server response is not returned to the client that initiates the request. The initiating client will instead get a 200 OK for all valid requests, acknowledging that the request has been received.

The text does say "asynchronous", but I want to make sure the above is clear.

**Comment by anderspitman** [comment]
@leggetter sorry for the extra long delay this time. If the client doesn't get the response, this isn't really the right list for hookdeck. A good smoke test is if you can serve a website and stream video from the server to the client.

**Comment by leggetter** [comment]
> @leggetter sorry for the extra long delay this time. If the client doesn't get the response, this isn't really the right list for hookdeck. A good smoke test is if you can serve a website and stream video from the server to the client.

Ah, ok, so just async receiving events/HTTP requests isn't enough.

The original ngrok README covered these use cases:

1. Temporarily sharing a website that is only running on your development machine
2. Demoing an app at a hackathon without deploying
3. Developing any services which consume webhooks (HTTP callbacks) by allowing you to replay those requests
4. Debugging and understanding any web service by inspecting the HTTP traffic
5. Running networked services on machines that are firewalled off from the internet

Hookdeck does fully support use case 3. But it sounds like your criteria is different.

Anyway, cheers for the great list.

**Comment by anderspitman** [comment]
It's not entirely out of scope, but the purpose of the list is definitely to focus on solutions for 5.

**Pull request closed without merging**
