### PR TITLE
Adding Beeceptor

### PR DESCRIPTION
**Pull request by ankitjaininfo**
I used [Beeceptor](https://beeceptor.com/) recently and find it to be a candidate for addition to this list. Beeceptor has local tunneling and, dynamic mocked response, simulating

### CODE REVIEW

**Comment by ankitjaininfo** [comment]
Did you get a chance to add this to the list?

**Comment by ankitjaininfo** [comment]
I think this can fit all your requirements

## The Dream

* Allows me to register a domain name and automatically points the records at the server running the tunnels. <<= All endpoints are sub-domain based
* Automatically sets up and manages HTTPS certificates (apex and subdomains) for the domain. <<== HTTP and HTTPs both supported on localhost.
* Provides a client tool that tunnels HTTP/TCP connections through the server without requiring root on the client. <<== Come with a CLI client. doesn't need `sudo`
* Provides a simple GUI interface to allow me to map X domain/subdomain to Y port on Z client, and proxy all connections to that domain. <<== Using the dashboard you can do all these mappings, and even mock a few API calls.

**Comment by ankitjaininfo** [comment]
@anderspitman  - let me know if you have got a chance to review this PR. If any changes are needed, let me know.

**Comment by ankitjaininfo** [comment]
@anderspitman : Here is the documentation on how to use tunnels with Beeceptor.

https://docs.beeceptor.com/docs/features-local-tunneling/

Beeceptor is an all-in-one HTTP debugging, mocking, tunneling, and reverse-proxy tool.

**Comment by ankitjaininfo** [comment]
Please check the above documentation link.

**Comment by anderspitman** [comment]
Thanks @ankitjaininfo!

**Pull request merged**
