### PR TITLE
Add ngtor

### PR DESCRIPTION
**Pull request by theborakompanioni**
Easily expose local services via Tor:
- Tunnel traffic via Tor to your locally running service
- All-in-one binary for macos, linux and windows

https://github.com/theborakompanioni/ngtor

### CODE REVIEW

**Comment by anderspitman** [comment]
Hey @theborakompanioni. Sorry for the delay. I tried to install ngtor but it's not clear to me how to use jitpack. The only instructions appear to be for adding into an existing JVM application using Gradle, sbt, etc, which doesn't make sense for downloading a program. If you can offer any clarification that would be helpful.

**Comment by theborakompanioni** [comment]
> Hey @theborakompanioni. Sorry for the delay. I tried to install ngtor but it's not clear to me how to use jitpack. The only instructions appear to be for adding into an existing JVM application using Gradle, sbt, etc, which doesn't make sense for downloading a program. If you can offer any clarification that would be helpful.

Hey @anderspitman! [Created a release](https://github.com/theborakompanioni/ngtor/releases/tag/v0.1.0) and added the binary. [Docs updated](https://github.com/theborakompanioni/ngtor#install). Thanks for the hint.
If you noticed anything else, or if you have additional feedback, please feel free to point it out :orange_heart:

**Comment by anderspitman** [comment]
Thanks @theborakompanioni! Very slick program. Note that I had to use Java 17 in order to run it. You might consider compiling it with an earlier version of java to make it work with older implementations, or at least document what the minimum required version is.

**Comment by anderspitman** [comment]
Ah perfect :+1:

**Pull request merged**
