### PR TITLE
Add Horizon Tunnel

### PR DESCRIPTION
**Pull request by bramvanhoutte**
Add [Horizon Tunnel](https://hrzn.run) to the paid options

### CODE REVIEW

**Comment by anderspitman** [comment]
Hi @bramvanhoutte, thanks for the contribution. Does Horizon have any particular features that would make someone want to use it over Cloudflare Tunnel or ngrok?

**Comment by anderspitman** [comment]
Thanks @bramvanhoutte!

**Comment by bramvanhoutte** [comment]
> Hi @bramvanhoutte, thanks for the contribution. Does Horizon have any particular features that would make someone want to use it over Cloudflare Tunnel or ngrok?

@anderspitman Missed the notification for this.

For Cloudflare you need domain registered there to make it work.
Cheaper than Ngrok.

**Comment by anderspitman** [comment]
Is that true about Cloudflare? I've definitely set up tunnels without using my own domain before.

**Pull request merged**
