### PR TITLE
Add gradio tunneling

### PR DESCRIPTION
**Pull request by arkohut**
A script to extract gradio share code from gradio. Make it available for non gradio programs.

### CODE REVIEW

**Comment by anderspitman** [comment]
Hi @arkohut, thanks for the contribution. Does gradio-tunneling have any particular features that make it stand out from alternatives on the list? Does it work for tunneling anything or only gradio apps?

**Comment by arkohut** [comment]
1. The particular feature is that it includes a free frp server from gradio. It is maintained by huggingface. For info can be found in [https://status.gradio.app/](https://status.gradio.app/).
2. The key feature of gradio tunneling is that it can be used without gradio app. It is just a frp solution, so can be used for anything.

**Comment by anderspitman** [comment]
@arkohut these are what I would call attributes or facts, not features. I'm specifically wondering why someone would use gradio rather than just using one of the many other options on the list, such as Cloudflare Tunnel or frp directly?

**Comment by arkohut** [comment]
I think using frp without setup your own frp server is a good feature. And I am not using Cloudflare not sure if it is as easy as one line of command. 

This gradio tunneling will setup a random domain and it is quite convenient for temporary demo sharing.

**Comment by anderspitman** [comment]
Hi again @arkohut, sorry for the delay. gradio-tunnel looks nice, but I'm concerned because I'm not sure the gradio folks would want people using their infrastructure for things other than gradio apps. Are you affiliated with gradio in some way?

**Comment by arkohut** [comment]
Good idea, I will contact them for this project.

**Comment by anderspitman** [comment]
Going to close this for now until we hear more.

**Pull request closed without merging**
