### PR TITLE
Add wiretap entry

### PR DESCRIPTION
**Pull request by luker983**
Wiretap is a transparent, VPN-like proxy server that tunnels traffic via WireGuard and requires no special privileges to run: https://github.com/sandialabs/wiretap

### CODE REVIEW

**Comment by anderspitman** [comment]
Hey @luker983, Wiretap looks really nice but seems to be more of a user space VPN tool than a tunneling solution? Is there an example of just setting up a tunnel I can look at?

**Comment by luker983** [comment]
Hey, thanks for taking a look. Wiretap is functionally similar to sshuttle, allowing for a user with root access on their local machine to tunnel layer-3 traffic through a remote host where the user does not have root. It accomplishes this with a userspace networking stack.

The base example is pretty much identical to how sshuttle works, but uses WireGuard/UDP so SSH is not required. It has some additional features like allowing users to chain multiple instances of Wiretap, reverse tunneling via SOCKS/static port forwarding, and Windows support.

If it's not a good fit I understand, just thought I'd propose it because sshuttle is on the list and Wiretap may serve as a better alternative in some cases.

**Comment by anderspitman** [comment]
@luker983 sorry this slipped through the cracks. Seems like a solid addition if you still want it merged

**Comment by luker983** [comment]
@anderspitman No worries at all. I'd still love to have it merged. Thanks!

**Pull request merged**
