### PR TITLE
Add ssh-j.com

### PR DESCRIPTION
**Pull request by ValdikSS**
No source code right now, but it will be published in a few next days (need to make it suitable for publication first).

### CODE REVIEW

**Comment by ValdikSS** [comment]
The code is up: https://bitbucket.org/ValdikSS/dropbear-sshj/

**Comment by anderspitman** [comment]
Hi @ValdikSS, thanks for the contribution. [ssh-j.com](ssh-j.com) looks down for me currently. What's the status of this project?

**Comment by ValdikSS** [comment]
Works fine for me. Do you try to open it with browser? It has only SSH, no web server.

**Comment by anderspitman** [comment]
Ah I see. So reading the source code it looks like you recommend using sish instead? Do you still want to add ssh-j to the list?

**Comment by ValdikSS** [comment]
Yes, it's a free service, and it works. sish does not provide public service, only self-hosted.

**Comment by anderspitman** [comment]
Sounds good. I added it here: https://github.com/anderspitman/awesome-tunneling/commit/89a1f28f79f65b37968870dea71a93958b8667dd

Just fixed some formatting and reworded a bit. Thanks!

**Pull request closed without merging**
