### PR TITLE
Add kcptun and tinc

### PR DESCRIPTION
**Pull request by ktaf**

### CODE REVIEW

**Comment by anderspitman** [comment]
Hi @ktaf. Sorry for the delay. Tinc looks like a good fit for the overlay section, but kcptun looks like a lower level tool for improving latency between two endpoints, which I'm not sure is very useful for the average selfhoster (which is the focus of the list). Would you agree?

**Comment by ktaf** [comment]
Hi, Yes I do.

**Comment by anderspitman** [comment]
In that case I'll modify the PR to add Tinc to the overlay section, but not at kcptun, if that's ok with you?

**Comment by ktaf** [comment]
Sure, no problem.

**Comment by anderspitman** [comment]
Great, thanks!

**Pull request merged**
